services:
  db:
    image: motorway-test-backend
    env_file: .env
    container_name: motorway-test-backend
    build:
      context: .
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
  app:
    container_name: motorway-challenge
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - NODE_ENV=$DOCKER_ENV
      - PORT=$DOCKER_PORT
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT:$REDIS_PORT
      - REDIS_USERNAME=$REDIS_USERNAME
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
    ports:
      - 5000:5000
    links:
      - db
      - redisServer
  redisServer:
    container_name: redisServer
    image: redis
    volumes:
      - redisServerdata:/data
volumes:
  my_dbdata:
  redisServerdata: